// Reference vocabulary of food names, grouped by the same category enum
// Product.category already uses (vegetables/fruits/grains/spices/dairy).
// This is purely an autocomplete suggestion list for the farmer product
// form — it does NOT drive market prices (see market/normalize.js's
// commodity list, which stays scoped to what's plausible as actual Indian
// mandi data). Free text entry is still allowed everywhere this is used.

const RAW = {
  vegetables: [
    'Acorn squash', 'Alfalfa sprouts', 'Amaranth greens', 'Ancho pepper', 'Artichoke', 'Arugula', 'Asparagus', 'Aubergine', 'Avocado', 'Bamboo shoots',
    'Bean sprouts', 'Beet greens', 'Beetroot', 'Belgian endive', 'Bok choy', 'Broccoli', 'Broccoli rabe', 'Brussels sprouts', 'Butternut squash', 'Cabbage',
    'Carrot', 'Cassava', 'Cauliflower', 'Celeriac', 'Celery', 'Chayote', 'Collard greens', 'Corn', 'Cucumber', 'Daikon',
    'Dandelion greens', 'Edamame', 'Endive', 'Fennel', 'Garlic', 'Ginger', 'Green bean', 'Green bell pepper', 'Green cabbage', 'Green onion',
    'Jalapeño', 'Jerusalem artichoke', 'Jicama', 'Kale', 'Kohlrabi', 'Leek', 'Lemongrass', 'Lettuce', 'Lotus root', 'Mushroom',
    'Mustard greens', 'Napa cabbage', 'Okra', 'Onion', 'Parsnip', 'Pea', 'Pea shoots', 'Poblano pepper', 'Potato', 'Pumpkin',
    'Radicchio', 'Radish', 'Rutabaga', 'Shallot', 'Snow pea', 'Sorrel', 'Spaghetti squash', 'Spinach', 'Spring onion', 'Sweet potato',
    'Swiss chard', 'Taro', 'Tomatillo', 'Tomato', 'Turnip', 'Watercress', 'Water chestnut', 'Winter squash', 'Yam', 'Zucchini',
    'Yellow squash', 'Yellow onion', 'Red onion', 'Red cabbage', 'Red bell pepper', 'Orange bell pepper', 'Yellow bell pepper', 'Purple cabbage', 'Savoy cabbage', 'Sunchoke',
    'Romanesco', 'Broccolini', 'Rapini', 'Mizuna', 'Tatsoi', 'Komatsuna', 'Bitter melon', 'Bottle gourd', 'Ridge gourd', 'Snake gourd',
    'Ash gourd', 'Ivy gourd', 'Pointed gourd', 'Sponge gourd', 'Drumstick pods', 'Raw banana', 'Green papaya', 'Green mango', 'Plantain', 'Green chickpea',
    'Water spinach', 'Malabar spinach', 'New Zealand spinach', 'Purslane', 'Fenugreek greens', 'Curry leaves', 'Amaranth leaves', 'Roselle leaves', 'Moringa leaves', 'Beetroot leaves',
    'Turnip greens', 'Radish greens', 'Carrot tops', 'Celery leaves', 'Broccoli leaves', 'Cauliflower leaves', 'Pumpkin leaves', 'Sweet potato leaves', 'Taro leaves',
    'Yardlong bean', 'Hyacinth bean', 'Lima bean', 'Fava bean', 'French bean', 'Runner bean', 'Wax bean', 'Roman bean', 'Adzuki bean', 'Mung bean',
    'Black-eyed pea', 'Cowpea', 'Pigeon pea', 'Cluster bean', 'Winged bean', 'Tepary bean', 'Cranberry bean', 'Navy bean', 'Kidney bean', 'Black bean',
    'Great Northern bean', 'Cannellini bean', 'Pinto bean', 'Anasazi bean', 'Appaloosa bean', 'Yellow pea', 'Green pea', 'Split pea', 'Garden pea',
    'English pea', 'Sugar snap pea', 'Purple podded pea', 'Borlotti bean', 'Flageolet bean', 'Moth bean', 'Urad bean', 'Black gram', 'Green gram', 'Horse gram',
    'Rice bean', 'Velvet bean', 'Jack bean', 'Sword bean', 'Soybean', 'Lentil sprouts', 'Chickpea sprouts', 'Radish sprouts', 'Broccoli sprouts',
    'Mustard sprouts', 'Clover sprouts', 'Sunflower shoots', 'Garlic scapes', 'Onion greens', 'Chive', 'Shiso leaves', 'Perilla leaves', 'Nasturtium leaves',
    'Banana blossom', 'Artichoke hearts', 'Palm hearts', 'Cactus pads', 'Nopal', 'Burdock root', 'Salsify', 'Black salsify', 'Skirret', 'Oca',
    'Ulluco', 'Mashua', 'Yacon', 'Arracacha', 'Malanga', 'Eddoe', 'Cocoyam', 'Cassava leaves', 'Sweet corn', 'Baby corn',
    'Red kuri squash', 'Delicata squash', 'Kabocha squash', 'Hubbard squash', 'Buttercup squash', 'Turban squash', 'Carnival squash', 'Pattypan squash', 'Chayote squash',
    'White asparagus', 'Purple asparagus', 'Green asparagus', 'Romanesco cauliflower', 'Purple cauliflower', 'Orange cauliflower', 'White cauliflower', 'Green cauliflower', 'Purple carrot', 'White carrot',
    // Named cultivars/varieties (garden-center style — specific enough for a
    // farmer to name a real listing after, e.g. "Tomato Cherokee Purple").
    'Artichoke Green Globe', 'Arugula Astro', 'Bean Stringless Bush', 'Beets Detroit Red', 'Beets Bulls Red', 'Broccoli Pack Pro',
    'Brussel Sprouts Jade Cross', 'Bush Bean Blue Lake', 'Cabbage Bravo', 'Cabbage Chinese Blues', 'Cabbage Golden Acre', 'Cabbage Stonehead',
    'Cabbage Storage #4', 'Cabbage Red Jewel', 'Cantaloupe Burpee Hybrid', 'Cauliflower Cheddar', 'Cauliflower Graffiti', 'Cauliflower Romanesco',
    'Cauliflower Snowcrown', 'Celeriac Brillant', 'Celery Tango', 'Collards Georgia', 'Cucamelon', 'Cucumber Burpee Hybrid II',
    'Cucumber Burpless 26', 'Cucumber Burpless Bush', 'Cucumber GherKing Gherkin', 'Cucumber Marketmore 76', 'Cucumber Patio Snacker',
    'Eggplant Classic', 'Eggplant Ghostbuster', 'Eggplant Ichiban', 'Eggplant Rosa Bianco', 'Endive Salad King', 'Escarole Full Heart',
    'Fennel, Florence', 'Gourd Small Formula Blend', 'Honeydew Early Dew Green', 'Kale Lacinato', 'Kale Scarletbor', 'Kale Vates',
    'Kolhrabi Grand Duke', 'Leek Large American Flag', 'Lettuce Alkindus Red Butterhead', 'Lettuce Bergams Green', 'Lettuce Bibb',
    'Lettuce Buttercrunch', 'Lettuce Cherokee', 'Lettuce Deer Tongue', 'Lettuce Freckles', 'Lettuce Galactic', 'Lettuce Ithaca',
    'Lettuce Fusion', 'Lettuce New Red Fire', 'Lettuce Muir', 'Lettuce Oakleaf', 'Lettuce Romaine, Breen', 'Lettuce Romaine, Green Forest',
    'Lettuce Ruby Sky', 'Lettuce Summertime', 'Lettuce Vulcan', 'Mustard Mizuna Miz America', 'Mustard Red Giant', 'Okra Cajun Delight',
    'Onion Candy', 'Onion Red Burgundy', 'Onion Walla Walla', 'Onion Warrior Bunching', 'Onion White Spanish', 'Onion Yellow Spanish',
    'Pak Choi Joi Choi', 'Pak Choi Red Pac', 'Peanut Carolina Jumbo', 'Pepper Big Bertha', 'Pepper California Wonder', 'Pepper California Wonder Yellow',
    'Pepper Candy Cane Red', 'Pepper Chocolate Beauty Bell', 'Pepper Cornito Giallo', 'Pepper Cubanelle', 'Pepper Giant Marconi', 'Pepper Gypsy',
    'Pepper Jupiter', 'Pepper King of the North', 'Pepper Lady Bell', 'Pepper Mad Hatter', 'Pepper Orange Sun Bell', 'Pepper Purple Beauty Bell',
    'Pepper Red Knight', 'Pepper Round of Hungary', 'Pepper Snackabella', 'Pepper Sweet Banana', 'Pepper Sweet Bite Size Red', 'Pepper Sweet Bite Size Yellow',
    'Pepper Hot Cayenne Large Red Thick', 'Pepper Hot Habanero Orange', 'Pepper Hot Holy Mole', 'Pepper Hot Hungarian Wax', 'Pepper Hot Jalapeno',
    'Pepper Hot Lemondrop', 'Pepper Hot Mucho Nacho', 'Pepper Hot Poblano', 'Pepper Hot Portugal', 'Pepper Hot Red Cherry Large', 'Pepper Hot Serrano Chili',
    'Pumpkin Baby Boo White', 'Pumpkin Jack-Be-Little', 'Pumpkin Jack-O-Lantern', 'Pumpkin Mystic Plus', 'Pumpkin Neck',
    'Squash Summer Scallop White Bush', 'Squash Summer Yellow Straightneck', 'Squash Summer Zucchini Aristocrat', 'Squash Summer Zucchini Eight Ball',
    'Squash Summer Zucchini Gold Rush', 'Squash Winter Acorn Table Princess', 'Squash Winter BonBon', 'Squash Winter Butternut Indian Brave',
    'Squash Winter Vegetable Spaghetti', 'Swiss Chard Bright Lights', 'Tomatillo Ground Toma Verde', 'Tomatillo Husk Ground Cherry',
    'Tomato Amish Paste', 'Tomato Better Boy', 'Tomato Big Beef', 'Tomato Black Russian', 'Tomato Brandywine Red Potato Leaf', 'Tomato Burpee Big Boy',
    'Tomato Bush Beefsteak', 'Tomato Bush Early Girl', 'Tomato Candyland Red', 'Tomato Celebrity', 'Tomato Delicious', 'Tomato Early Girl',
    'Tomato Evergreen', 'Tomato First Lady II', 'Tomato Giant Tree', 'Tomato Grape', 'Tomato Great White', 'Tomato Health Kick',
    'Tomato Heirloom Yellow Cherry', 'Tomato Indigo Cherry Drops', 'Tomato Jetstar', 'Tomato Juliet', 'Tomato Lemon Boy', 'Tomato Little Napoli',
    'Tomato Long Keeper', 'Tomato Mator Sandwich', 'Tomato Mortgage Lifter', 'Tomato Mountain Pride', 'Tomato Mr. Stripey', 'Tomato Old German',
    'Tomato Orange', 'Tomato Oxheart', 'Tomato Pineapple', 'Tomato Pink Girl', 'Tomato Roma', 'Tomato Rutgers', 'Tomato Striped Stuffer (Pepper)',
    'Tomato Sugar Lump', 'Tomato Sunsugar', 'Tomato Supersonic', 'Tomato Supersteak Hybrid', 'Tomato Supersweet 100', "Tomato Sweet'N Neat Cherry Red",
    'Tomato Tidy Treats', 'Tomato Tomatoberry', 'Tomato Very Cherry Cascade', 'Tomato Yellow Pear',
    'Watermelon Crimson Sweet', 'Watermelon Sangria', 'Watermelon Sugar Baby', 'Watermelon Seedless',
    // Burpee-brand varieties
    'Cucumber Fresh Pickles', 'Eggplant Early Midnight', 'Eggplant Meatball', 'Eggplant Patio Baby', 'Pea Masterpiece', 'Pepper Big Daddy',
    'Pepper Bush Habanero', 'Pepper Confetti', 'Pepper Gold Standard', 'Pepper Jalapeno Gigante', 'Pepper Jungle Parrot', 'Pepper Lemon Dream',
    'Pepper Sweet Heat', 'Pepper Tangerine Dream', 'Pepper Thunderbolt Sweet', 'Pepper Zavory Hot',
    'Tomato Baby Boomer', 'Tomato Big Daddy', 'Tomato Big Mama', 'Tomato Brandy Boy', 'Tomato Bushsteak', 'Tomato Cherry Punch',
    'Tomato Fourth of July', 'Tomato Fresh Salsa', 'Tomato Homeslice', 'Tomato Indigo Sun', 'Tomato Mighty Sweet', 'Tomato Power Pops',
    'Tomato San Marzano', 'Tomato Solar Power', 'Tomato SuperSauce', 'Tomato Sweet Seedless', 'Tomato Sweetheart of the Patio', 'Tomato Tasti-Lee',
  ],
  fruits: [
    'Apple', 'Apricot', 'Avocado', 'Banana', 'Blackberry', 'Blueberry', 'Cantaloupe', 'Cherry', 'Clementine', 'Coconut',
    'Cranberry', 'Date', 'Dragon fruit', 'Durian', 'Elderberry', 'Fig', 'Gooseberry', 'Grape', 'Grapefruit', 'Guava',
    'Jackfruit', 'Kiwi', 'Kumquat', 'Lemon', 'Lime', 'Lychee', 'Mango', 'Mangosteen', 'Melon', 'Mulberry',
    'Nectarine', 'Orange', 'Papaya', 'Passion fruit', 'Peach', 'Pear', 'Persimmon', 'Pineapple', 'Plum', 'Pomegranate',
    'Pomelo', 'Quince', 'Raspberry', 'Star fruit', 'Strawberry', 'Tangerine', 'Watermelon', 'Blackcurrant', 'Redcurrant', 'White currant',
    'Acai berry', 'Acerola', 'Bilberry', 'Boysenberry', 'Cloudberry', 'Goji berry', 'Huckleberry', 'Loganberry', 'Marionberry',
    'Salmonberry', 'Tayberry', 'Youngberry', 'Chokeberry', 'Aronia berry', 'Buffaloberry', 'Serviceberry', 'Juneberry', 'Wineberry', 'Barberry',
    'Jujube', 'Loquat', 'Longan', 'Rambutan', 'Salak', 'Sapodilla', 'Sapote', 'Mamey sapote', 'White sapote', 'Black sapote',
    'Canistel', 'Cherimoya', 'Custard apple', 'Soursop', 'Sugar apple', 'Atemoya', 'Abiu', 'Lucuma', 'Pepino melon', 'Tamarillo',
    'Feijoa', 'Jabuticaba', 'Mangaba', 'Cupuaçu', 'Grumichama', 'Pitanga', 'Surinam cherry', 'Brazilian cherry', 'Rose apple', 'Wax apple',
    'Java plum', 'Black plum', 'Indian jujube', 'Wood apple', 'Bael', 'Karonda', 'Phalsa', 'Jamun', 'Ber', 'Amla',
    'Indian gooseberry', 'Kokum', 'Tamarind', 'Bilimbi', 'Ambarella', 'Santol', 'Langsat', 'Lanzones', 'Pulasan', "Buddha's hand",
    'Finger lime', 'Meyer lemon', 'Key lime', 'Makrut lime', 'Calamansi', 'Yuzu', 'Sudachi', 'Kabosu', 'Bergamot', 'Citron',
    'Blood orange', 'Seville orange', 'Bitter orange', 'Cara Cara orange', 'Navel orange', 'Valencia orange', 'Mandarin', 'Satsuma', 'Dancy tangerine', 'Honey tangerine',
    'Minneola tangelo', 'Orlando tangelo', 'Tangelo', 'Ugli fruit', 'Pink grapefruit', 'White grapefruit', 'Oroblanco', 'Sweet lime', 'Mosambi', 'Kaffir lime',
    'Red banana', 'Plantain', "Lady Finger banana", 'Cavendish banana', 'Gros Michel banana', 'Blue Java banana', 'Manzano banana', 'Burro banana', "Fe'i banana", 'Pisang Raja',
    'Apple banana', 'Namwa banana', 'Lakatan banana', 'Saba banana', 'Praying Hands banana', 'Ice cream banana', 'Musa banana', 'Kepok banana', 'Bluggoe banana', 'Horn plantain',
    'Alphonso mango', 'Kesar mango', 'Dasheri mango', 'Langra mango', 'Banganapalli mango', 'Totapuri mango', 'Chaunsa mango', 'Sindhri mango', 'Himsagar mango', 'Malgoa mango',
    'Neelam mango', 'Amrapali mango', 'Mallika mango', 'Raspuri mango', 'Imam Pasand mango', 'Pairi mango', 'Fazli mango', 'Kent mango', 'Keitt mango', 'Haden mango',
    'Tommy Atkins mango', 'Ataulfo mango', 'Francis mango', 'Palmer mango', 'Nam Dok Mai mango', 'Valencia Pride mango', 'Edward mango', 'Osteen mango', 'Julie mango', 'Carrie mango',
    'Fuji apple', 'Gala apple', 'Granny Smith apple', 'Honeycrisp apple', 'Pink Lady apple', 'Braeburn apple', 'Golden Delicious apple', 'Red Delicious apple', 'McIntosh apple', 'Cortland apple',
    'Empire apple', 'Jonagold apple', 'Jonathan apple', 'Ambrosia apple', 'Jazz apple', 'Envy apple', 'Winesap apple', 'Ginger Gold apple', "Cox's Orange Pippin", 'Gravenstein apple',
    'Conference pear', 'Bartlett pear', 'Anjou pear', 'Bosc pear', 'Comice pear', 'Asian pear', 'Seckel pear', 'Forelle pear', 'Concorde pear', "Clapp's Favorite pear",
    'Santa Rosa plum', 'Black Amber plum', 'Greengage plum', 'Mirabelle plum', 'Damson plum', 'Victoria plum', 'Satsuma plum', 'Elephant Heart plum', 'Black Doris plum', 'Italian prune plum',
    'Rainier cherry', 'Bing cherry', 'Montmorency cherry', 'Morello cherry', 'Stella cherry', 'Lapins cherry', 'Sweetheart cherry', 'Chelan cherry', 'Skeena cherry', 'Balaton cherry',
    'Rockmelon', 'Honeydew', 'Galia melon', 'Charentais melon', 'Canary melon', 'Crenshaw melon', 'Casaba melon', 'Santa Claus melon', 'Hami melon', 'Piel de Sapo melon',
    'Grapes', 'Muskmelon', 'Sapota', 'Dates', 'Olive',
  ],
  grains: [
    'Rice', 'Brown rice', 'White rice', 'Basmati rice', 'Jasmine rice', 'Arborio rice', 'Carnaroli rice', 'Vialone Nano rice', 'Sushi rice', 'Sticky rice',
    'Black rice', 'Red rice', 'Wild rice', 'Forbidden rice', 'Bomba rice', 'Calasparra rice', 'Valencia rice', 'Glutinous rice', 'Parboiled rice', 'Converted rice',
    'Short-grain rice', 'Medium-grain rice', 'Long-grain rice', 'Wehani rice', 'Purple rice', 'Camargue red rice', 'Bhutanese red rice', 'Koshihikari rice', 'Calrose rice', 'Akitakomachi rice',
    'Brown basmati rice', 'Golden basmati rice', 'Sona masuri rice', 'Ponni rice', 'Matta rice', 'Seeraga samba rice', 'Gobindobhog rice', 'Jeera rice', 'Kolam rice', 'Indrayani rice',
    'Jowar', 'Sorghum', 'Pearl millet', 'Finger millet', 'Foxtail millet', 'Proso millet', 'Barnyard millet', 'Kodo millet', 'Little millet', 'Browntop millet',
    'Teff', 'Quinoa', 'Amaranth', 'Buckwheat', 'Barley', 'Rye', 'Oats', 'Wheat', 'Spelt', 'Einkorn',
    'Emmer', 'Kamut', 'Farro', 'Freekeh', 'Triticale', 'Cornmeal', 'Polenta', 'Maize', 'Popcorn', 'Dent corn',
    'Flint corn', 'Sweet corn', 'Blue corn', 'White corn', 'Yellow corn', 'Red corn', 'Purple corn', 'Hominy', 'Grits', 'Steel-cut oats',
    'Rolled oats', 'Quick oats', 'Oat groats', 'Oat bran', 'Wheat berries', 'Rye berries', 'Barley groats', 'Pearl barley', 'Pot barley', 'Hulled barley',
    'Scotch barley', 'Barley flakes', 'Rye flakes', 'Wheat flakes', 'Spelt flakes', 'Quinoa flakes', 'Buckwheat groats', 'Buckwheat flakes', 'Amaranth grain', 'Teff grain',
    'Millet flour', 'Sorghum flour', 'Rice flour', 'Brown rice flour', 'Oat flour', 'Barley flour', 'Rye flour', 'Wheat flour', 'Whole wheat flour', 'Spelt flour',
    'Einkorn flour', 'Emmer flour', 'Kamut flour', 'Buckwheat flour', 'Quinoa flour', 'Amaranth flour', 'Corn flour', 'Masa harina', 'Semolina',
    'Durum wheat', 'Hard red wheat', 'Hard white wheat', 'Soft white wheat', 'Red fife wheat', 'Turkey red wheat', 'Sonora wheat', 'Einkorn wheat', 'Emmer wheat', 'Khorasan wheat',
    'Freekeh wheat', 'Bulgar wheat', 'Bulgur', 'Cracked wheat', 'Couscous', 'Israeli couscous', 'Pearl couscous', 'Whole wheat couscous', 'Malted barley', 'Barley malt',
    'Rye malt', 'Wheat malt', 'Wheat bran', 'Rice bran', 'Corn bran', 'Barley bran', 'Quinoa tricolor', 'Red quinoa',
    'White quinoa', 'Black quinoa', 'Golden quinoa', 'Royal quinoa', 'Puffed rice', 'Puffed wheat', 'Puffed millet', 'Puffed quinoa', 'Puffed amaranth', 'Popped sorghum',
    'Rice flakes', 'Poha', 'Flattened rice', 'Red poha', 'White poha', 'Aval', 'Murmura', 'Rice vermicelli', 'Rice noodles', 'Brown rice noodles',
    'Soba', 'Udon noodles', 'Somen noodles', 'Glass noodles', 'Corn flakes', 'Bran flakes', 'Oat flakes', 'Multigrain flakes', 'Muesli', 'Granola',
    'Buckwheat noodles', 'Millet noodles', 'Sorghum noodles', 'Quinoa pasta', 'Whole wheat pasta', 'Durum semolina',
    'Macaroni wheat', 'Bread wheat', 'Pasta wheat',
    // Indian cereal/millet/pulse names (with common regional alt-names)
    'Maize / Corn', 'Sorghum / Jowar', 'Pearl Millet / Bajra', 'Finger Millet / Ragi',
    'Chickpeas / Chana', 'Bengal Gram', 'Black Gram / Urad', 'Green Gram / Moong', 'Red Gram / Toor',
    'Lentils / Masoor', 'Kidney Beans / Rajma', 'Black-Eyed Peas / Lobia', 'Cowpea', 'Moth Beans / Matki',
    'Horse Gram / Kulith', 'Field Beans / Val', 'Hyacinth Beans', 'Soybeans', 'Peas',
    'Broad Beans / Fava Beans', 'Pinto Beans', 'Navy Beans', 'Adzuki Beans', 'Mung Beans', 'Lima Beans',
    'Broken Rice', 'Semolina / Rava', 'Oatmeal', 'Gram Flour / Besan',
  ],
  spices: [
    'Black pepper', 'White pepper', 'Green peppercorn', 'Pink peppercorn', 'Long pepper', 'Cubeb pepper', 'Sichuan pepper', 'Sansho pepper', 'Grains of paradise', 'Allspice',
    'Cardamom', 'Green cardamom', 'Black cardamom', 'Cinnamon', 'Ceylon cinnamon', 'Cassia', 'Clove', 'Nutmeg', 'Mace', 'Star anise',
    'Anise seed', 'Fennel seed', 'Cumin', 'Caraway', 'Coriander seed', 'Dill seed', 'Fenugreek seed', 'Mustard seed', 'Celery seed', 'Nigella seed',
    'Ajwain', 'Carom seed', 'Asafoetida', 'Turmeric', 'Ginger', 'Galangal', 'Fingerroot', 'Horseradish', 'Wasabi', 'Saffron',
    'Paprika', 'Smoked paprika', 'Sweet paprika', 'Hot paprika', 'Cayenne', 'Chili powder', 'Red pepper flakes', 'Aleppo pepper', 'Chipotle', 'Ancho chili',
    'Guajillo chili', 'Pasilla chili', 'Mulato chili', 'Arbol chili', 'Cascabel chili', "Bird's eye chili", 'Thai chili', 'Kashmiri chili', 'Byadgi chili', 'Guntur chili',
    'Black mustard', 'Brown mustard', 'Yellow mustard', 'White mustard', 'Fenugreek', 'Curry powder', 'Garam masala', 'Chaat masala', 'Panch phoron', 'Ras el hanout',
    'Baharat', "Za'atar", 'Herbes de Provence', 'Chinese five-spice', 'Japanese seven-spice', 'Shichimi togarashi', 'Berbere', 'Harissa spice', 'Advieh', 'Dukkah',
    'Sumac', 'Amchur', 'Anardana', 'Kokum', 'Tamarind powder', 'Mango powder', 'Loomi', 'Dried lime', 'Methi', 'Kasuri methi',
    'Cumin powder', 'Coriander powder', 'Turmeric powder', 'Ginger powder', 'Garlic powder', 'Onion powder', 'Mustard powder', 'Fenugreek powder', 'Fennel powder', 'Cardamom powder',
    'Cinnamon powder', 'Clove powder', 'Nutmeg powder', 'Mace powder', 'Black pepper powder', 'White pepper powder', 'Saffron threads', 'Saffron powder', 'Vanilla bean', 'Vanilla powder',
    'Bay leaf', 'Indian bay leaf', 'Curry leaf', 'Kaffir lime leaf', 'Makrut lime leaf', 'Dried oregano', 'Oregano', 'Thyme', 'Rosemary', 'Sage',
    'Basil', 'Sweet basil', 'Holy basil', 'Thai basil', 'Tarragon', 'Marjoram', 'Savory', 'Mint', 'Peppermint', 'Spearmint',
    'Dill weed', 'Parsley', 'Cilantro', 'Chervil', 'Lovage', 'Lemongrass', 'Pandan leaf', 'Ramps', 'Chive', 'Epazote',
    'Annatto', 'Achiote', 'Fenugreek leaves', 'Dried mint', 'Dried parsley', 'Dried dill', 'Dried cilantro', 'Dried basil', 'Dried thyme', 'Dried rosemary',
    'Dried sage', 'Dried tarragon', 'Dried marjoram', 'Dried savory', 'Juniper berry', 'Sumac berry', 'Schisandra berry', 'Mastic', 'Mahleb', 'Tonka bean',
    'Cubeb', 'Camphor', 'Galangal powder', 'Fingerroot powder', 'Licorice root', 'Licorice powder', 'Mugwort', 'Wormwood', 'Hyssop',
    'Sorrel', 'Lemon verbena', 'Lemon balm', 'Rose petals', 'Hibiscus', 'Lavender', 'Safflower', 'Nigella flower', 'Calendula', 'Orange peel',
    'Lemon peel', 'Bitter orange peel', 'Dried orange peel', 'Dried lemon peel', 'Dried lime peel', 'Tamarind seed', 'Poppy seed', 'Sesame seed', 'Black sesame', 'White sesame',
    'Brown sesame', 'Chia seed', 'Flaxseed', 'Hemp seed', 'Wasabi powder', 'Horseradish powder', 'Beet powder', 'Chipotle powder', 'Ancho powder', 'Guajillo powder',
    'Cayenne powder', 'Aleppo pepper flakes',
  ],
  dairy: [
    'Milk', 'Whole milk', 'Skim milk', 'Low-fat milk', 'Reduced-fat milk', 'Buffalo milk', 'Goat milk', 'Sheep milk', 'Camel milk', 'Yak milk',
    'Condensed milk', 'Sweetened condensed milk', 'Evaporated milk', 'Powdered milk', 'Milk powder', 'Nonfat dry milk', 'Buttermilk', 'Cultured buttermilk', 'Kefir', 'Ayran',
    'Lassi', 'Plain yogurt', 'Greek yogurt', 'Icelandic yogurt', 'Skyr', 'Bulgarian yogurt', 'Turkish yogurt', 'Lebanese yogurt', 'Indian dahi', 'Curd',
    'Strained yogurt', 'Set yogurt', 'Stirred yogurt', 'Drinking yogurt', 'Fruit yogurt', 'Vanilla yogurt', 'Natural yogurt', 'Low-fat yogurt', 'Whole-milk yogurt', 'Probiotic yogurt',
    'Sour cream', 'Crème fraîche', 'Clotted cream', 'Double cream', 'Heavy cream', 'Whipping cream', 'Light cream', 'Single cream', 'Table cream', 'Coffee cream',
    'Half-and-half', 'Mexican crema', 'Mascarpone', 'Ricotta', 'Cottage cheese', 'Cream cheese', 'Neufchâtel', 'Quark', 'Fromage blanc', 'Fromage frais',
    'Paneer', 'Chhena', 'Chhurpi', 'Kalari', 'Bandel', 'Dahi', 'Mishti doi', 'Shrikhand', 'Basundi', 'Rabri',
    'Kheer', 'Payasam', 'Kulfi', 'Malai', 'Khoya', 'Mawa', 'Ghee', 'Butter', 'Clarified butter', 'Cultured butter',
    'Salted butter', 'Unsalted butter', 'European butter', 'Sweet cream butter', 'Whey butter', 'Brown butter', 'Cheddar', 'Mild cheddar', 'Sharp cheddar', 'Aged cheddar',
    'White cheddar', 'Red Leicester', 'Double Gloucester', 'Gloucester', 'Cheshire', 'Lancashire', 'Wensleydale', 'Stilton', 'Blue Stilton', 'Shropshire Blue',
    'Caerphilly', 'Red Windsor', 'Sage Derby', 'Derby cheese', 'Colby', 'Colby-Jack', 'Monterey Jack',
    'Pepper Jack', 'Havarti', 'Danish Havarti', 'Tilsit', 'Edam', 'Gouda', 'Aged Gouda', 'Smoked Gouda', 'Maasdam', 'Leerdammer',
    'Emmental', 'Emmentaler', 'Gruyère', 'Comté', 'Beaufort', 'Raclette', 'Appenzeller', 'Vacherin Fribourgeois', 'Tomme de Savoie', 'Reblochon',
    'Brie', 'Brie de Meaux', 'Brie de Melun', 'Camembert', 'Neufchâtel cheese', 'Chaource', 'Coulommiers', 'Munster', 'Livarot', "Pont-l'Évêque",
    'Maroilles', 'Époisses', 'Taleggio', 'Fontina', 'Asiago', 'Montasio', 'Provolone', 'Scamorza', 'Mozzarella', 'Buffalo mozzarella',
    'Burrata', 'Stracciatella', 'Bocconcini', 'Caciocavallo', 'Pecorino Romano', 'Pecorino Toscano', 'Pecorino Sardo', 'Parmigiano-Reggiano', 'Grana Padano', 'Castelmagno',
    'Gorgonzola', 'Gorgonzola Dolce', 'Gorgonzola Piccante', 'Dolcelatte', 'Roquefort', "Bleu d'Auvergne", 'Bleu de Gex', 'Bleu des Causses', "Fourme d'Ambert", 'Fourme de Montbrison',
    'Danablu', 'Danish Blue', 'Cabrales', 'Valdeón', 'Idiazabal', 'Manchego', 'Mahón', 'Tetilla', 'Garrotxa', 'Majorero',
    'Queso Fresco', 'Queso Blanco', 'Queso Oaxaca', 'Queso Panela', 'Queso Cotija', 'Queso Chihuahua', 'Queso de Bola', 'Queso Asadero', 'Queso Menonita', 'Quesillo',
    'Feta', 'Greek Feta', 'Bulgarian Feta', 'Telemea', 'Sirene', 'Halloumi', 'Akkawi', 'Nabulsi', 'Labneh', 'Shanklish',
    'Kaseri', 'Kefalotyri', 'Graviera', 'Mizithra', 'Anthotyros', 'Manouri', 'Kashkaval', 'Kashkaval Vitosha', 'Brinza', 'Bryndza',
    'Ragusano', 'Raschera', 'Robiola', 'Stracchino', 'Quartirolo Lombardo', 'Bitto', 'Fiore Sardo', 'Sbrinz', 'Tête de Moine', "L'Etivaz",
    'Vacherin Mont d\'Or', 'Saint-Nectaire', 'Saint-Marcellin', 'Saint-Félicien', 'Morbier', 'Cantal', 'Salers', 'Laguiole', 'Abondance',
    'Beaufort d\'Alpage', 'Tomme de Brebis', 'Ossau-Iraty', 'Pouligny-Saint-Pierre', 'Valençay', 'Crottin de Chavignol', 'Sainte-Maure de Touraine', 'Selles-sur-Cher', 'Banon', 'Pélardon',
    'Fresh cheese', 'Washed-rind cheese', 'Bloomy-rind cheese', 'Blue cheese', 'Hard cheese', 'Semi-hard cheese', 'Soft cheese', 'String cheese', 'Processed cheese', 'Cheese curds',
    'Whey', 'Whey protein', 'Whey cheese', 'Mysost', 'Brunost', 'Gjetost', 'Primost', 'Nøkkelost', 'Jarlsberg', 'Norvegia',
  ],
};

// Case-insensitive de-dupe, preserving first-seen order — same rule the
// source list was generated with.
function dedupe(list) {
  const seen = new Set();
  return list.filter(name => {
    const key = name.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export const FOOD_NAMES = Object.fromEntries(
  Object.entries(RAW).map(([category, names]) => [category, dedupe(names)])
);

export function foodNamesFor(category) {
  return FOOD_NAMES[category] || [];
}
